# Generated by Django 5.0.7 on 2024-07-18 11:56

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='blog/blog')),
                ('status', models.CharField(choices=[('pb', 'Publish'), ('ds', 'Draft')], default='pb', max_length=4)),
                ('published_date', models.DateTimeField(default=datetime.datetime(2024, 7, 18, 11, 56, 9, 920732, tzinfo=datetime.timezone.utc))),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(to='blog.commints')),
            ],
        ),
    ]
