# Generated by Django 5.0.7 on 2024-07-18 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(null=True, to='blog.commints'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 12, 15, 34, 935469, tzinfo=datetime.timezone.utc)),
        ),
    ]
